# Generated by Django 3.1.4 on 2021-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_auto_20210119_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
